# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "laminar-demo"  #TODO: Change to your own name if you want to deploy your app to fly.io
kill_signal = "SIGINT"
kill_timeout = 5

[env]

[build]

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    force_https = true
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    grace_period = "30s"
    interval = "30s"
    method = "get"
    timeout = "10s"
    path = "/ping"

#  [[statics]]
#    guest_path = "/server/src/main/resources/static/assets"
#    url_prefix = "/assets"
